version: '3.2'
services:
  mysql:
    extends:
      file: mysql/docker-compose.yml
      service: mysql
  airflow:
    extends:
      file: airflow/docker-compose.yml
  cocktaildb_api:
    extends:
      file: apis/docker-compose.yml
      service: cocktaildb_api