version: '3.2'
services:
  mysql:
    image: mysql:8
    command:
      - --secure-file-priv=/tmp/data
      - --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password!
    volumes:
      - type: bind
        source: ./init/
        target: /docker-entrypoint-initdb.d/
      - type: bind
        source: ../data/temp
        target: /tmp/data
    networks:
      - cocktaildb-network


networks:
  cocktaildb-network:
    external: true